// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiqKoacPzv-TwoEkBoHLXoDdeAtc_zzMI',
    appId: '1:584905864976:android:6cec5a88898ff9ad2d9795',
    messagingSenderId: '584905864976',
    projectId: 'sarpras-smkn',
    storageBucket: 'sarpras-smkn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjHP5v4PN7LplqIqhzY0vgB_JT1sDiBG4',
    appId: '1:584905864976:ios:36da2adbac19e27e2d9795',
    messagingSenderId: '584905864976',
    projectId: 'sarpras-smkn',
    storageBucket: 'sarpras-smkn.firebasestorage.app',
    iosBundleId: 'com.example.peminjamanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvJ-8ow_50cMMZV_TwLt4fDOKqucPCN88',
    appId: '1:584905864976:web:4a8c160492e3b9fd2d9795',
    messagingSenderId: '584905864976',
    projectId: 'sarpras-smkn',
    authDomain: 'sarpras-smkn.firebaseapp.com',
    storageBucket: 'sarpras-smkn.firebasestorage.app',
  );
}
